# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"  # Set to the Python version you need

    # Step 3: Install make and dependencies using make install
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install make  # Ensure make is available
        make install  # Use the install target from the Makefile

    # Step 4: Run the Flask server (add a sleep to allow it to start properly)
    - name: Run the server
      run: |
        make run &  # Run the Flask app in the background
        sleep 10    # Wait 10 seconds for the server to start

    # Optional Step 5: Test the server (you can replace this with actual tests)
    - name: Test server
      run: |
        curl -f http://localhost:3000  # Check if the server is running (replace with your actual test command)
